#
#▀██▀  ▀█▀           ██                                          ▀██  ▀██▀▀█▄   ▀██                  ▀██                      
# ██    █  ▄▄ ▄▄▄   ▄▄▄  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄   ▄▄▄▄   ▄▄▄▄    ██   ██   ██   ██    ▄▄▄     ▄▄▄▄   ██  ▄▄    ▄▄▄▄  ▄▄▄ ▄▄  
# ██    █   ██  ██   ██   ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀ ██▄ ▀  ▀▀ ▄██   ██   ██▀▀▀█▄   ██  ▄█  ▀█▄ ▄█   ▀▀  ██ ▄▀   ▄█▄▄▄██  ██▀ ▀▀ 
# ██    █   ██  ██   ██    ▀█▄█   ██       ██     ▄ ▀█▄▄ ▄█▀ ██   ██   ██    ██  ██  ██   ██ ██       ██▀█▄   ██       ██     
#  ▀█▄▄▀   ▄██▄ ██▄ ▄██▄    ▀█     ▀█▄▄▄▀ ▄██▄    █▀▄▄█▀ ▀█▄▄▀█▀ ▄██▄ ▄██▄▄▄█▀  ▄██▄  ▀█▄▄█▀  ▀█▄▄▄▀ ▄██▄ ██▄  ▀█▄▄▄▀ ▄██▄    
#

settings:
  # Форматирование текста.
  # LEGACY - цвет через & и hex &#
  # LEGACY_ADVANCED - улучшенный аналог legacy с поддержкой &## формата hex
  # MINIMESSAGE - цвет через <цвет>
  # MINIMESSAGE был добавлен в новых версиях (1.17+)
  serializer: LEGACY
  # Режим работы с прокси.
  # Если включено - все оповещения из notify будут отправляться по всей вашей сети серверов
  proxy: false
  # Включить ли поддержку PlaceholderAPI?
  papi_support: true
  # Включить ли отправку анонимной статистики (пожалуйста не отключайте)
  enable_metrics: true
  # Проверять ли наличие обновлений (пожалуйста не отключайте)
  update_checker: true
  # Включение/отключение модулей плагина
  enable_chat_module: true
  enable_symbol_module: true
  enable_command_module: true
  # Настройка кастомной папки для плагина. Именно по этому пути будут храниться данные
  custom_plugin_folder:
    enable: false
    path: '/root/server/plugins/UniversalBlocker/'
  # Отключать ли сервер при отключении плагина
  shutdown_on_disable: false

# На каких игроков не будут действовать никакие запреты (можно оставить пустым, это снизит нагрузку)
excluded_players:
  - 'Overwrite'
  - 'test99999'