name: UniversalBlockerUltimate
main: ru.overwrite.ublocker.UniversalBlocker
author: OverwriteMC
version: '${project.version}'
api-version: 1.16
folia-supported: true
softdepend: [ WorldGuard ]
commands:
  universalblocker:
    aliases: [ ublocker, ub ]
permissions:
  ublocker.bypass.*:
    children:
      ublocker.bypass.commands: true
      ublocker.bypass.symbols: true
      ublocker.bypass.chat: true