#
#▀██▀  ▀█▀           ██                                          ▀██  ▀██▀▀█▄   ▀██                  ▀██                      
# ██    █  ▄▄ ▄▄▄   ▄▄▄  ▄▄▄▄ ▄▄▄   ▄▄▄▄  ▄▄▄ ▄▄   ▄▄▄▄   ▄▄▄▄    ██   ██   ██   ██    ▄▄▄     ▄▄▄▄   ██  ▄▄    ▄▄▄▄  ▄▄▄ ▄▄  
# ██    █   ██  ██   ██   ▀█▄  █  ▄█▄▄▄██  ██▀ ▀▀ ██▄ ▀  ▀▀ ▄██   ██   ██▀▀▀█▄   ██  ▄█  ▀█▄ ▄█   ▀▀  ██ ▄▀   ▄█▄▄▄██  ██▀ ▀▀ 
# ██    █   ██  ██   ██    ▀█▄█   ██       ██     ▄ ▀█▄▄ ▄█▀ ██   ██   ██    ██  ██  ██   ██ ██       ██▀█▄   ██       ██     
#  ▀█▄▄▀   ▄██▄ ██▄ ▄██▄    ▀█     ▀█▄▄▄▀ ▄██▄    █▀▄▄█▀ ▀█▄▄▀█▀ ▄██▄ ▄██▄▄▄█▀  ▄██▄  ▀█▄▄█▀  ▀█▄▄▄▀ ▄██▄ ██▄  ▀█▄▄▄▀ ▄██▄    
#

settings: 
  # Включить ли отправку анонимной статистики (пожалуйста не отключайте)
  enable-metrics: true
  # Проверять ли наличие обновлений (пожалуйста не отключайте)
  update-checker: true
  # Оповещать ли администраторов о "нарушениях" игроков
  notify: true
  # Отключать ли сервер при отключении плагина
  shutdown-on-disable: false
  # Включение/выключение функций плагина
  enable-words-blocker: true
  enable-numbers-check: true
  enable-allowed-chars: true
  enable-command-blocker: true
  enable-console-blocker: true
  enable-rcon-blocker: true
  enable-symbol-blocker: true
  enable-sign-symbol-blocker: true
  # Блокирует просмотр плагинов читом и через прочие способы
  enable-tab-complere-blocker: true 
  # Блокировка команд через : (bukkit:pl и т.п.)
  enable-blocksyntax: true
  # Скрывать ли заблокированные команды из таб комплита (доступно только с 1.13)
  hide-blocked-commands-from-tab-comple: true
  # Включить ли тайтлы при "нарушениях" игроков
  enable-titles: true
  # Включить ли звуковые оповещения при "нарушениях" игроков
  enable-sounds: true
  # Включите это если что-то не работает и смотрите что будет
  debug: false
    
# На каких игроков не будут действовать никакие запреты (можно оставить пустым)
excluded-players:
  - 'Overwrite'
  - 'test99999'

chat-settings:
  # Какие символы можно писать в чате
  allowed-chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ ~`1!2@3#4$5%6^7&§89(0)-_=+*|[{]}\;:"',<.>/?!№
  # Максимальное кол-во цифр в сообщении
  maxmsg-numbers: 7
  # Проверять ли строго
  # Если включено - плагин будет блокировать все сообщения с большим колличеством цифр в сообщении
  # Если отключено - плагин будет блокировать только попытки написать IP (по типу 228.13.37.69 - число цифр в IP 11, а разрешено 7)
  strict-number-chek: true
  # Запрещенные слова
  ban-words:
   - 'хуй'
   - 'еблан'
   - 'говно'
   - 'залупа'
   - 'шлюха'
   - 'пизда'
   - '-run'
   - '-con'
   - '-opme'
   - 'LOyoujoLIHACKACTIVITED'

# Запрещенные символы в командах
symbols:
  # Список запрещенных символов
  blocked-symbols:
   - '-ff'
   - '-uu'
   - '.*'
   - '**'
  # На какие команды это не распространяется (можно оставить пустым)
  excluded-commands:
   - 'l'
   - 'login'
   - 'reg'
   - 'register'
   - 'pas'
  # Список запрещенных символов на табличках
  blocked-sign-symbols:
   - '.ru'
   - '[hack]'
   - '[opka]'
   
# Запрещенные команды
blocked-commands:
  # Можно прописывать, имея право ublocker.bypass.commands
  lite:
   - 'pl'
   - 'plugins'
   - 'ver'
   - 'version'
   - 'about'
   - '?'
   - 'bukkit:ver'
   - 'bukkit:version'
   - 'bukkit:about'
   - 'bukkit:?'
   - 'bukkit:help'
  # Не сможет писать никто, кроме игроков из списка 'excluded-players'
  full:
   - 'op'
   - 'deop'
   - 'packet'
   - 'protocol'
   - 'execute'
   - 'sudo'
  # Блокировка команд консоли
  console:
   - 'rg remove -w world spawn'
   - 'kill *'
   - 'gm 1 *'
   - 'op @a'
  # Блокировка команд rcon
  rcon:
   - 'rg remove -w world spawn'
   - 'kill *'
   - 'gm 1 *'
   - 'op @a'
  # Блокировка заполнения аргументов к командам
  args-tab-complete:
   - 'ver'
   - 'version'
   - 'about'
   - '?'
   - 'bukkit:ver'
   - 'bukkit:version'
   - 'bukkit:about'
   - 'bukkit:?'
   - 'bukkit:help'
  
# Настройка звкуков
sounds:
  # Звук оповещения админов
  admin-notify:
    sound: BLOCK_NOTE_BLOCK_PLING
    volume: 1.0
    pitch: 1.0
  # Звук при заблокированной команде
  blocked-command:
    sound: ENTITY_ITEM_BREAK
    volume: 1.0
    pitch: 1.0
  # Звук при заблокированном символе
  blocked-symbol:
    sound: ENTITY_ITEM_BREAK
    volume: 1.0
    pitch: 1.0
  # Звук при запрещенном действии в чате
  blocked-chat:
    sound: BLOCK_CHAIN_BREAK
    volume: 1.0
    pitch: 1.0